### PR TITLE
Fix fuzzer CI build. Add regression check.

### PR DESCRIPTION
**Pull request by sashashura**
The issue with current CI is that ``-DCMAKE_C_FLAGS=-fsanitize=address`` doesn't really build the fuzzer. This commit makes it build always to avoid regressions if it stops compiling because of other refactoring changes.

### CODE REVIEW

**Comment by lipnitsk** [comment]
Why did you remove `build_and_check_with_asan` from CI and `BUILD_FUZZER` cmake option? Fuzzer build should be option-guarded so that normal users don't bother building fuzz targets.

**Comment by sashashura** [comment]
There was a mistake in `build_and_check_with_asan` it wasn't building fuzz target same as `build_and_check`.
I have added `main` function declaration guarded by `#ifndef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION` to make it build for normal users.
Building it always like tests has the benefit that it makes sure it compiles if anything changes.

**Comment by sashashura** [comment]
If you are strongly against that, I can return the conditional flag back. I have another pending change that actually needs a separate workflow job. It can be used to build fuzz.

**Comment by sashashura** [comment]
It shows the commit before my comment, but I pushed it just now. Getting the optional flag back is an easy fix on top of the changes. Please, let me know what you think.

**Comment by sashashura** [comment]
I have added a reproducer from the yet not merged fix and my regression test works as expected :) - the check has failed.
@lipnitsk so what do you think about this pull request?

**Comment by lipnitsk** [comment]
@sashashura If you bring the `BUILD_FUZZER` option back so fuzzer doesn't build by default I'm ok with merging this.

**Pull request merged**
