### PR TITLE
Make fuzzer build with Centipede engine

### PR DESCRIPTION
**Pull request by sashashura**
A followup change to make the fuzzer compile with one more engine - Centipede. It seems it assumes the fuzzer must be compiled with C++. Otherwise it [errors with undefined reference](https://github.com/google/oss-fuzz/actions/runs/6487688543/job/17618539131?pr=11104). I have changed the fuzzer to compile with C++ and link libcue as C library.

### CODE REVIEW

**Comment by koltiradw** [comment]
i think u need to rename fuzz.c to fuzz,cpp in CMakeLists,txt.

**Comment by koltiradw** [comment]
I think your fuzz target is not entirely correct.
It's better to expand the intermediate buffer by 1 than to overwrite the last byte from the fuzzer. Like [here](https://github.com/koltiradw/oss-sydr-fuzz/blob/ab2ff59b69653c5ada8cdced504a6993f1c20507/projects/libcue/fuzz_cue_parse_string.c#L24)

**Comment by lipnitsk** [comment]
Seems a bit risky for a quick merge, can we let this brew a bit? This should not block oss-fuzz integration, right?

**Comment by koltiradw** [comment]
Yep. This shouldn't block integration, but it will make the process neater.

**Comment by sashashura** [comment]
> Seems a bit risky for a quick merge, can we let this brew a bit? This should not block oss-fuzz integration, right?

Sure, I can disable Centipede for now.

**Comment by sashashura** [comment]
> I think your fuzz target is not entirely correct. It's better to expand the intermediate buffer by 1 than to overwrite the last byte from the fuzzer. Like [here](https://github.com/koltiradw/oss-sydr-fuzz/blob/ab2ff59b69653c5ada8cdced504a6993f1c20507/projects/libcue/fuzz_cue_parse_string.c#L24).

Agree, the last byte is cut off. I think I'll make the improvement in the next batch. At the same time any zero byte in the middle of buffer may cut the rest because it is treated as a string. I have been contemplating skipping `memcpy` to improve the performance if `memchr` finds any zero byte,  but it looks like there is no significant speedup.

**Comment by lipnitsk** [comment]
Please rebase on top of tree and I can re-evaluate merging this.

**Pull request merged**
